services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./dataset:/app/dataset
      - ./examples:/app/examples
      - ./output:/app/output
